apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
spec:
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - name: api-demo
        image: katahtonic/api-demo:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api-demo-service
spec:
  selector:
    app: api-demo
  ports:
  - port: 80
    targetPort: 8080
